//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLBookStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TwinkleStoreEntities : DbContext
    {
        public TwinkleStoreEntities()
            : base("name=TwinkleStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerItemsHistory> CustomerItemsHistories { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserItem> UserItems { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    
        public virtual ObjectResult<string> usp_Qualified20Discount(Nullable<int> custId)
        {
            var custIdParameter = custId.HasValue ?
                new ObjectParameter("CustId", custId) :
                new ObjectParameter("CustId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_Qualified20Discount", custIdParameter);
        }
    
        public virtual ObjectResult<usp_UpCmgBdayCust_Result> usp_UpCmgBdayCust()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_UpCmgBdayCust_Result>("usp_UpCmgBdayCust");
        }
    
        public virtual ObjectResult<usp_AnualCustBilling_Result> usp_AnualCustBilling()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AnualCustBilling_Result>("usp_AnualCustBilling");
        }
    }
}
