//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserItem
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public Nullable<int> NoOfItems { get; set; }
        public Nullable<decimal> DiscAmmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
